[package]
name = "hb"
version = "0.4.1"
authors = ["Mark Pritchard <mpritcha@gmail.com>"]
edition = "2024"

[dependencies]
clap = "4.6.4"
env_logger = "0.11.11"
hdrhistogram = "7.6.0"
indicatif = "0.18.6"
log = "0.4.33"
rand = "0.10.2"
ureq = { version = "3.3.0", features = ["charset"] }
url = "2.5.8"

[dev-dependencies]
assert_approx_eq = "1.1.0"
